### PR TITLE
Composer refactor

### PR DESCRIPTION
**Pull request by stevector**
This PR brings in the lcache library with Composer. It fully commits composer.lock file and a `--no-dev` version of the `vendor` directory. After a git-to-svn script is completed in https://github.com/pantheon-systems/solr-power/issues/15, we can repurpose the work done there to then remove the vendor dir from this repo as well.

### CODE REVIEW

**Comment by stevector** [comment]
@danielbachhuber any idea why Travis is not running again on this branch? https://travis-ci.org/lcache/wp-lcache/pull_requests

**Comment by danielbachhuber** [comment]
> any idea why Travis is not running again on this branch?

Maybe it's because there's a second `.travis.yml` committed?

**Comment by stevector** [comment]
Hmm, Travis is running now. The only changes I made were merging master and switching the dependency on lcache to `dev-master`. @danielbachhuber do you think `dev-master` is appropriate for now given the pace of changes in lcache? We can make a follow up issue to switch it back to only using releases.

**Comment by stevector** [comment]
@danielbachhuber, I'm assigning over to you for review/merging.

**Comment by danielbachhuber** [comment]
Closing in favor of #40

**Pull request closed without merging**
