### PR TITLE
Prefix LCache tables based on WP table prefix

### LINKED ISSUE #19: Prefix LCache tables based on WordPress' table prefix
We might want to make sure the tables are added with a prefix, to ensure two WordPress installs can share the same database.

### PR DESCRIPTION
**Pull request by danielbachhuber**
This will let two WordPress instances share the same database, but use
different LCache data.

Fixes #19

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@stevector #reviewmerge

**Comment by stevector** [comment]
@danielbachhuber Is there a way we can update the table name for sites with the plugin already installed? Here's what I'm getting when bringing this branch to a site with the plugin installed already:

```
Warning: LCache Database: Failed to fetch events : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pantheon.wp_lcache_events' doesn't exist in /srv/bindings/51196b77518341518b8b60f95813ac46/code/wp-content/plugins/wp-lcache/vendor/lcache/lcache/src/DatabaseL2.php on line 130
```

**Comment by danielbachhuber** [comment]
> Is there a way we can update the table name for sites with the plugin already installed?

Not easily. I don't think it's necessary either, given we haven't tagged an initial release yet.

**Comment by stevector** [comment]
ok, merging.

**Pull request merged**
