### PR TITLE
Offer a groups implementation based on LCache bin implementation

### LINKED ISSUE #6: Add support for LCache tags
We can expose them in WordPress as cache groups. It should work similarly to how WP Redis has enabled cache groups.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #6

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@stevector #reviewmerge

**Comment by stevector** [comment]
I'm unassigning from myself until tests are passing again.

**Comment by danielbachhuber** [comment]
> I'm unassigning from myself until tests are passing again.

@stevector Why can't you code review something that doesn't have passing tests?

**Comment by danielbachhuber** [comment]
@stevector Build is passing again

**Comment by stevector** [comment]
Sorry, I was just assuming more changes were coming. I should have looked closer and seen that the scope of the previous test failures was small.

**Pull request merged**
